### ISSUE TITLE
[FEATURE] Add support for `app_home_opened`

### ISSUE THREAD

**Issue by JVenberg** [slackapi/deno-slack-api#112]
**Description of the problem being solved**

Hello! I was curious if there is a plan to support Slack App Home's in workflow automation. 

**Alternative solutions**

I assume it's not as simple as just adding the `app_home_opened` event, as it would also require enabling the app home in the app's `feature` configuration.

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-api/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @JVenberg! Thanks for submitting this request 😄 

As far as I know, there are currently no plans on the roadmap to add in this functionality for Automations, as mentioned in this issue (https://github.com/slackapi/deno-slack-sdk/issues/182). However, it is definitely something that has been requested and I know it's been in discussions, but doesn't seem like there are any plans to tackle it as of right now. In the meantime, I recommend using a regular App with the `app_home_opened` event to accomplish what you need.

It would be helpful to get your insight into what use case you're trying to use the app home for in automations - this can help give the team insight for future plans :)

**Comment by filmaj** [comment]
Since we're already tracking this in https://github.com/slackapi/deno-slack-sdk/issues/182, I will close this issue. Feel free to post additional comments / use cases / needs in that issue thread.

**Comment by rkhaslarov** [comment]
Guys, any updates? Why the support of the deno-sdk is so poor, we've created app via that and you suggest to recreate the app on old engine?

**Comment by zimeg** [comment]
@rkhaslarov We don't have updates to share around support for app home right now, but I also want to note that the Deno SDK has focused more on supporting apps with [workflows](https://docs.slack.dev/workflows/) while Bolt apps embrace other parts of the Events API.

Both frameworks and SDKs continue to be supported, but the available features might differ. A breakdown on these differences are available here: https://docs.slack.dev/workflows/comparing-workflows-apps
