### ISSUE TITLE
[BUG] Can't access CLA assistant

### ISSUE THREAD

**Issue by whywaita** [slackapi/deno-slack-api#84]
### Describe the bug
I can't sign CLA from [Contributing guidelines](../CONTRIBUTING.md). I found an error.

I want to contribute but I can't now.

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
Access to https://cla-assistant.io/slackapi/deno-slack-api

### Expected behavior

A developer can begin to sign CLA.

#### Screenshots

![sc](https://github.com/slackapi/deno-slack-api/assets/4568341/bb95675f-d99b-4049-bc9b-4b7a266ba741)

#### Reproducible in:

deno-slack-api version:

Deno version:

OS version(s):

**Comment by whywaita** [comment]
@filmaj @WilliamBergamin Please check a site (CLA assistant) configuration or a contribution guide 👀

**Comment by seratch** [comment]
@whywaita, apologies for our delayed response here.

We've switched from the CLA assistant to the Salesforce one; however, it seems that we haven't updated the contribution guide yet 🤦 . Our team will resolve this later, so please proceed with your pull request and sign our newest CLA. Moreover, please remember that, if you plan to make significant changes, you should start a discussion before sending such code changes. Thank you for your interest!

**Comment by whywaita** [comment]
@seratch Thank you for your quick comment!

I got it, I will open an issue and pull-request.

**Comment by seratch** [comment]
Thank you very much for pointing this issue out. We've resolved the issue on the contribution guide ✅
